version: '2'

services:
   mysql:
     image: mysql:latest
     container_name: mysql
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: $WORDPRESS_PASSWORD

   wordpress:
     depends_on:
       - mysql
     image: wordpress:latest
     container_name: wordpress
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: $WORDPRESS_PASSWORD
volumes:
    db_data: